### ISSUE TITLE
How to modify the manifest_template.conf

### ISSUE THREAD

**Issue by michoug** [lmlui/Jorg#6]
Hi,
I'm quite confused by the fact that while giving reads is forward and reverse as fastq.gz, mirabait indicates that they are empty.

`jorg -b VAR_61_metabat_446.fa --forward ../Trim/20210409.B-o24408_1_07-VAR_61_mtg_sed_R1_val_1.fastq.gz --reverse ../Trim/20210409.B-o24408_1_07-VAR_61_mtg_sed_R2_val_2.fastq.gz -c 23 -i 5`

```
*Start: Jorg iteration # 1*
Start: recruiting reads with mirabait
End: recruiting reads with mirabait - 0 seconds elapsed.
Recruiting reads with mirabait appears to have finished successfully.
Start: check if fastq file empty.
Error: fastq file empty.
```

I suppose that this has something to do with the  `manifest_template.conf` file, should I modify it beforehand? I don't know if mirabait can work with gz file?
Best
Greg

**Comment by michoug** [comment]
Hi,
It's an issue with mirabait on my computer so I had to compile it and it worked
Best
Greg

**Comment by lmlui** [comment]
Hi Greg,

Sorry I didn't get back to you yesterday.  I'm glad that you were able to figure out the issue.

Best,

Lauren

**Comment by RunJiaJi** [comment]
```
User environment details:
MIRA path: /public/home/userMTB/miniconda3/envs/jorgnew/bin/mira
MIRA version: V5rc1
MIRABAIT path: /public/home/userMTB/miniconda3/envs/jorgnew/bin/mirabait
MIRABAIT version: V5rc1
seqtk path: /public/home/userMTB/miniconda3/envs/jorgnew/bin/seqtk
 
***Start running Jorg***
Start: make manifest file for MIRA
End: make manifest file for MIRA
Start: generating new directory named 'Iterations'
End: generating new directory named 'Iterations'
 
*Start: Jorg iteration # 1*
Start: recruiting reads with mirabait
End: recruiting reads with mirabait - 0 seconds elapsed.
Recruiting reads with mirabait appears to have finished successfully.
Start: check if fastq file empty.
Error: fastq file empty.
```
Hi guys, I've encountered the same situation. Is this because of mirabait is not compiled properly? BTW, I used the precompiled binary version of mira [mira_V5rc1_linux-gnu_x86_64_static.tar.bz2](https://github.com/bachev/mira/releases). If so, what should I do? 
Thank you!
Best
Runjia
