### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by gecko1990** [lmlui/Jorg#7]
Dear developers,

thanks a lot for this tool. I wanted to use Jorg for improving the quality of a fragmented MAG from a marine metagenome. I get the tool running but after two iteration the tool finishes and there is nothing inside the *.out.fasta file. I am unsure if the problem is that MIRA cannot resolve such a fragmented genome or that I am doing something wrong. I send you the different logs I found. 
[Jorg_Bin_11719_4_ANME_1-contigs.fa_mar-23-nov-2021-17-38-57-CET.log](https://github.com/lmlui/Jorg/files/7603865/Jorg_Bin_11719_4_ANME_1-contigs.fa_mar-23-nov-2021-17-38-57-CET.log)
[mirabait_iteration_2.log](https://github.com/lmlui/Jorg/files/7603867/mirabait_iteration_2.log)
[mirabait_iteration_1.log](https://github.com/lmlui/Jorg/files/7603868/mirabait_iteration_1.log)
.

**Comment by lmlui** [comment]
Hi @gecko1990,

Can you give me a little more information about your MAG?  How many contigs and do you know the average coverage?

**Comment by gecko1990** [comment]
Yes, the MAG has 174 contigs and an average coverage of 140.

**Comment by lmlui** [comment]
Likely your average minimum coverage is set too high.  Try lowering the value ( -c parameter).  What is likely happening is none of the contigs are passing the average coverage filter and that's why the second iteration doesn't have any contigs.   I hope that helps!  Otherwise you might have a "chaos" bin.

**Comment by tnn111** [comment]
> Yes, the MAG has 174 contigs and an average coverage of 140.

Could you please respond to Lauren's suggestion?. It's likely the minimum required coverage is set too high. This can easily happen. I'd also caution you that we generally do not use this tool with that high a number of contigs.

Please try the suggestion and let's know what happens. Set the minimum required coverage down to maybe 1/3rd of the coverage of the lowest coverage contain.

Thanks.

**Comment by gecko1990** [comment]
Thanks! I tried a couple of times using a lower coverage, but now I tried with a much lower threshold. I wanted to ask what is you definition of coverage. Maybe you indicate it in the paper, but it would be great to know the exact definition, since some programs have different "versions" for this parameter.

**Comment by tnn111** [comment]
It’s the number of reads covering a given position on a contig. We usually average over each contig. I hope it works for you now.

**Comment by gecko1990** [comment]
It didn't work. It ran, but the output was the same as the initial bin according to the md5sum.

**Comment by lmlui** [comment]
Did you check the iterations.txt output file?  It's possible that this bin cannot be improved much and is at the "idempotence" state as described in the paper.  The iterations.txt file has a cumulative_length column and you can see what happened at each iteration. It is also possible that the last iteration is not the best to choose from.

**Comment by gecko1990** [comment]
I did, but there is nothing written in that file. The output is:
```
contig_name     length  GC_percent      cumulative_length
Iteration 1
```
I have the feeling that my bins are probably too fragmented for this procedure. You can close the issue, if you think no improvement is possible.

**Comment by lmlui** [comment]
Yes, I think that unfortunately that the bin is not passing the minimum checks after the MIRA assembly to continue, and that's why you aren't getting any output.  It's also possible that there is another issue but I can't tell unless I see the log file.  I'll close the issue for now, but if you want to continue to look into getting the program to run feel free to open it again.
